trainer: forces

dataset:
  - src: newlmdb/
    normalize_labels: True
    target_mean: 0
    target_std: 1
    grad_target_mean: 0.0
    grad_target_std: 1
  - src: newlmdb/

logger: wandb

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
