trainer: forces

dataset:
  - src: /checkpoint/ocp/train/2m/
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: /checkpoint/ocp/val/id_30k/

logger: wandb

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True

model:
  name: allegromap
  compile_model: False
  # symmetry
  l_max: 1
  parity: o3_full   
  BesselBasis_trainable: true
  num_basis: 8
  PolynomialCutoff_p: 6
  # Allegro layers:
  num_layers: 1
  env_embed_multiplicity: 8
  embed_initial_edge: true
  two_body_latent_mlp_latent_dimensions: [32, 64, 128]
  two_body_latent_mlp_nonlinearity: silu
  two_body_latent_mlp_initialization: uniform
  latent_mlp_latent_dimensions: [128]
  latent_mlp_nonlinearity: silu
  latent_mlp_initialization: uniform
  latent_resnet: true
  env_embed_mlp_latent_dimensions: []
  env_embed_mlp_nonlinearity: null
  env_embed_mlp_initialization: uniform
  # - end allegro layers -
  # Final MLP to go from Allegro latent space to edge energies:
  edge_eng_mlp_latent_dimensions: [32]
  edge_eng_mlp_nonlinearity: null
  edge_eng_mlp_initialization: uniform
  use_sc: true
  cutoff: 6.0
  direct_forces: False
  regress_forces: True
  use_pbc: True
  max_neighbors: 50
  ave_num_neighbors: null
  atom_map: ["O","C","H"]

optim:
  batch_size: 4
  eval_batch_size: 4
  num_workers: 4
  lr_initial: 5.e-3
  max_epochs: 80
  eval_every: 1000
  load_balancing: atoms
  optimizer: AdamW
  optimizer_params: {"amsgrad": True, "weight_decay": 0.0}
  ema_decay: 0.999
  force_coefficient: 100
  energy_coefficient: 1
  scheduler: ReduceLROnPlateau
  loss_energy: mae
  loss_force: l2mae

  patience: 3
  factor: 0.8
  mode: min
